In [1]:
import numpy as np


In [2]:
data = np.random.randn(4, 2)

In [3]:
data 


array([[ 0.77716031,  0.63979503],
       [ 0.11941727, -1.13060959],
       [-0.13663027,  1.34515759],
       [ 0.41570306,  0.01915722]])

In [4]:
data * 10 #vectorized computation

array([[  7.77160306,   6.39795035],
       [  1.19417273, -11.30609593],
       [ -1.36630271,  13.45157593],
       [  4.15703057,   0.19157221]])

In [5]:
data + data  #vectorized computation

array([[ 1.55432061,  1.27959007],
       [ 0.23883455, -2.26121919],
       [-0.27326054,  2.69031519],
       [ 0.83140611,  0.03831444]])

In [6]:
data.shape  #check shape of array; reads like: a container list with 4 lists (as elements) containing 2 items in each of the 4 lists.

(4, 2)

In [7]:
data.dtype    #object describing the data type of an array

dtype('float64')

In [8]:
data1 = [10, 4, 3, 7, 21]

In [9]:
array1 = np.array(data1)   #makes an nd array:  (pass in any sequence-like object)

In [10]:
array1   # 1 dimensional array

array([10,  4,  3,  7, 21])

In [11]:
data2 = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

In [12]:
array2 = np.array(data2)

In [13]:
array2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
array2.ndim    #checks dimension; 2 dimensional array

2

In [15]:
data3 = [[[6,7,8,],[1,2,3],[3,4,5]]]

In [16]:
array3 = np.array(data3)

In [17]:
array3

array([[[6, 7, 8],
        [1, 2, 3],
        [3, 4, 5]]])

In [18]:
array3.ndim  # checks dimension; 3 dimensional array

3

In [19]:
array3.shape # checks shape; here: 2d array; 1 set of 3 lists containing 3 items in each list

(1, 3, 3)

In [20]:
data4 = [[[10,11,12,13],[14,15,16,17],[18,19,20,21],[22,23,24,25],[26,27,28,29]]]

In [21]:
array4 = np.array(data4)

In [22]:
array4

array([[[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21],
        [22, 23, 24, 25],
        [26, 27, 28, 29]]])

In [23]:
array4.ndim #checks dimension; 3 dimensional

3

In [24]:
array4.shape #checks shape; here: 3 d array; 1 set of 5 nested lists, 4 items in each list

(1, 5, 4)

In [25]:
data5 = [[[1,2], [3,4], [5,6], [7,8]],[[9,10], [11,12], [13,14], [15,16]]]

In [26]:
array5 = np.array(data5)

In [27]:
array5

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [28]:
array5.ndim # checks dimension; 3 dimensional

3

In [29]:
array5.shape #checks shape; here: 3d array; 2 sets of 4 nested lists with 2 items in each list

(2, 4, 2)

In [30]:
np.zeros(20)  

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [31]:
np.zeros(5,2) # forgot the parens!

TypeError: data type not understood

In [32]:
np.zeros((5,2))  # testing out shape 1 with zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [33]:
np.zeros((2,5,2)) # testing out shape 2 with zeros

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [34]:
np.ones(2, 10, 4)  # forgot the parens again!

TypeError: data type not understood

In [35]:
np.ones((2,10,1))  # testing out shape 3 with ones

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [36]:
np.ones((3, 2, 10))  # testing out shape for with ones

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [37]:
data6 = [[[[1,2], [3,4], [5,6], [7,8]],[[9,10], [11,12]]],[[[1,2], [3,4], [5,6], [7,8]],[[9,10], [11,12]]]]

In [38]:
array6 = np.array(data6)

In [39]:
array6  # testing out a set of a set of a set-- did not go as planned, looks like it returned a Python object, not float64?

array([[list([[1, 2], [3, 4], [5, 6], [7, 8]]),
        list([[9, 10], [11, 12]])],
       [list([[1, 2], [3, 4], [5, 6], [7, 8]]),
        list([[9, 10], [11, 12]])]], dtype=object)

In [40]:
array6.ndim   

2

In [41]:
array6.shape

(2, 2)

In [42]:
np.arange(12)   #create nd array using arange(built-in range function)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
arr1= np.array([1,2,3], dtype=np.float64)

In [44]:
arr1.dtype

dtype('float64')

In [45]:
int_arr = arr1.astype(np.int32)   #cast array from one type (float64) to another (int32)

In [46]:
int_arr.dtype  #check data type

dtype('int32')

In [47]:
arr7 = np.arange(12)  #stored array from above

In [48]:
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [49]:
arr7[3]  # access item at index

3

In [50]:
arr7[4:8]    # access slice on 1d array

array([4, 5, 6, 7])

In [51]:
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
arr7[4:8] = 502   # assign scalar to a slice, broadcasts to entire selection; !!Data is not copied, reflects in source array

In [53]:
arr7  # scalar value reflects in source array!

array([  0,   1,   2,   3, 502, 502, 502, 502,   8,   9,  10,  11])

In [54]:
sli_arr7 = arr7[4:8]  # create/store slice that I assigned a scalar value in [52]

In [55]:
sli_arr7   # slice label points to 502, assigned scalar value from [52]

array([502, 502, 502, 502])

In [56]:
sli_arr7 = 99999  # assign new scalar value to slice label

In [57]:
arr7   # source array does not reflect new scalar value of sli_arr7

array([  0,   1,   2,   3, 502, 502, 502, 502,   8,   9,  10,  11])

In [58]:
sli_arr7   # slice label references new scalar value

99999

In [59]:
arr7[4:8]   # no change to slice, retains old scalar value of sli_arr7

array([502, 502, 502, 502])

In [60]:
sli_arr7[1] = 7373

TypeError: 'int' object does not support item assignment

In [61]:
sli_arr7 = arr7[4:8]  # corrected error, reassigned to original slice

In [62]:
sli_arr7

array([502, 502, 502, 502])

In [63]:
sli_arr7[1] = 4567     # index changes in slice reflect in source array

In [64]:
arr7  # 1st (counting from 0 index) item of slice list of 4 items [502, 502, 502, 502] changed to 4567 from 502

array([   0,    1,    2,    3,  502, 4567,  502,  502,    8,    9,   10,
         11])

In [65]:
sli_arr7[:]= 1985

In [66]:
arr7

array([   0,    1,    2,    3, 1985, 1985, 1985, 1985,    8,    9,   10,
         11])